### ISSUE TITLE
Function pointers as function parameters are not recognized in C

### ISSUE THREAD

**Issue by deg0nz** [christophschlosser/doxdocgen#10]
When i give a function pointer as parameter to a function in C, the parameter is given as `@param (my_pointer` to the doxygen comment.

Here's an example:

``` C
/**
 * @brief 
 * 
 * (Detailed description)
 * 
 * @param (my_function_pointer
 */
void foo_bar(void (*my_function_pointer) (unsigned int arg1, char arg2))
```
Maybe this should look like `@param *my_function_pointer`? I actually don't know.
I could check how Sublime Text's Doxygen plugin [DoxyDoxygen](https://packagecontrol.io/packages/DoxyDoxygen) acts in these situations and give you feedback if you want to.

**Comment by christophschlosser** [comment]
Thank you again for taking the time to report this!

I will take a look at the Sublime Plugin myself and maybe I can find something in the Doxygen Documentation as well.

**Comment by rowanG077** [comment]
It should just look like my_function_pointer afaik.

**Comment by rowanG077** [comment]
Things get a lot harder once we have to account for function pointers. See this as an example.

`int (*idputs(int (*puts)(const char *)))(const char *);`

This is a declaration which takes a function pointer as an argument and also returns a function pointer.

**Comment by christophschlosser** [comment]
Well the return case is really tricky.
