### ISSUE TITLE
Support Visual Studio

### ISSUE THREAD

**Issue by gh-fb** [christophschlosser/doxdocgen#100]
# Description

Any change of supporting not only Visual Studio Code but also Visual Studio (e.g. Visual Studio Professional)

**Comment by christophschlosser** [comment]
If Microsoft allows to run VS Code extensions in Visual Studio then yes absolutely. Right now it‘s not possible as far as I know.
Porting it to Visual Studio doesn‘t work for ne either because I don‘t own a Windows PC.
