### ISSUE TITLE
Macro in Arguments

### ISSUE THREAD

**Issue by kamilpok** [christophschlosser/doxdocgen#101]
# Description

Macros in arguments are not parsed correctly

## Code example

```Cpp

#define P(ptrtype) ptrtype *
void test(P(int) a);
```

### Expected result

```Cpp
/*!*****************************************************************************
 * \brief 
 * 
 * \param a 
 ******************************************************************************/

```

### Actual result

```Cpp
/*!*****************************************************************************
 * \brief 
 * 
 ******************************************************************************/

```

**Comment by christophschlosser** [comment]
This is obviously a bug, but I'm not sure it is one we can fix.

Since Microsoft does not expose the code model through their native language server it's not possible to have stuff like this. Same reason we can not have documentation on mouseover.

Only solution I think here would be to use an alternative language server for a clang codemodell and try to parse it this way.

**Comment by kamilpok** [comment]
The type is not used in the output. Can it be just skipped?

This might be useful: https://github.com/christophschlosser/doxdocgen/pull/23#issuecomment-341932606

**Comment by rowanG077** [comment]
Well since macros are just some identifier or some identifier followed by parenthesis we could parse this. But like I said in the @kamilpok references this might not be inline with what is actually going on and since the macro can basically do anything.

**Comment by christophschlosser** [comment]
To be honest, I don't think there is a way to do this without having a codemodel available.

The macro you wrote could also be like this:

```C++
#define P(type, var) type* var
void foo(P(myType, a));

// or
#define P(var, type) type* var
void foo(P(a, myType));
```

There may be a possibility to have a guess for standard types but as soon as you get to custom types there is just no way to find out what is what by simply parsing the method signature string.
Macros are rarely defined in place as well and without a codemodel the addon can not access other documents except for the open ones.
