### ISSUE TITLE
The copyright tag cannot get the value of the other tags such as {author} {email} 

### ISSUE THREAD

**Issue by EatonLin** [christophschlosser/doxdocgen#103]
Hi, i think it would be convenience to modify copyright tag like this: 
"doxdocgen.generic.authorEmail": "Eaton@myemail.net",
"doxdocgen.generic.authorName": "Eaton",
"doxdocgen.file.copyrightTag": [
        "@copyright Copyright (c) {year} {author} ({email})"
 ],
But i got this weird copyright value in my file: @copyright Copyright (c) 2019 {author} ({email}), did i make mistake?

**Comment by christophschlosser** [comment]
As you can read in the documentation of the "doxdocgen.file.copyrightTag" key:

> // File copyright documentation tag.  Array of strings will be converted to one line per element.  Can template {year}.

And from your pasted string the year was correctly replaced. The others inserted as string, just as described in the documentation.
