### ISSUE TITLE
Trigger sequence does nothing

### ISSUE THREAD

**Issue by FauthD** [christophschlosser/doxdocgen#106]
Hi,
after installing from inside vs-code, the default trigger sequence "/**" does not cause any action.
I tried on Windows and Linux.
Perhaps there is some extra settings?
With CNTRL-SHIFT-P and entering "dox" there are no settings visible in vs-code.

Also created a file doxdocgen.json in the User dir (where the other json files are) with contents copied from git (.md). Perhaps that file should go into the .vscode dir inside project? But I expect the default to work at least.

Thanks a million, Dieter

**Comment by christophschlosser** [comment]
If you can not see any settings in your preferences menu of VS Code something went probably wrong with the install.

Doxdocgen does not maintain a separate config file but relies 100% on the mechanisms provided by VS Code.

Could you please provide some detail on what version of VS Code and doxdocgen you are using?
Also what is the output in the developer console of VS Code?

**Comment by marcelkalinowski** [comment]
I have the same problem. VS Code: 1.33.1, doxdocgen: 0.4.2

**Comment by christophschlosser** [comment]
You don't see the settings either?
What OS are you running on?
Is there output in the developer tools console?

**Comment by ronnystarkware** [comment]
I have the same problem. I can see the settings, but no triggering and CRTL-SHIFT-P writing "dox" shows nothing.
Linux, VSCode 1.34, doxdocgen: 0.4.2

**Comment by christophschlosser** [comment]
Closing this because of a lack of information
