### ISSUE TITLE
Feature suggest: Indent option

### ISSUE THREAD

**Issue by rms95** [christophschlosser/doxdocgen#107]
# Description

Quite a few code projects I worked on use indentation in doxygen blocks. It would be nice to have an option to do this in the extension.

## Code example

The blocks I use generally looks like this:
```C
/**
 * @brief       Print my ints
 *              One more line
 * 
 * @param[in]   The int to print
 * @param[in]   Another integer
 * @return      A number
 */
int printMyInt(int i1, int i2);
```
Where the total width from " * " to the start of the description is 16 characters wide, which fits most keys.

### Actual result

```Cpp
/**
 * @brief 
 * 
 * @param i1 
 * @param i2 
 * @return int 
 */
int printMyInt(int i1, int i2);
```

Having an option named something like doxdocgen.generic.indentWith which pads spaces till the specified width, defaulted to 0, would address this. This would not change the behaviour to anyone who doesn't want to use the feature. As far as I am aware padding spaces like this is allowed in Doxygen.

The reason I prefer this notation in some projects is that APIs with a lot of parameters with a lot of documentation generally get significantly more readable.

**Comment by christophschlosser** [comment]
Thank you for the great suggestion!

I will take a look into it.

**Comment by christophschlosser** [comment]
Hi @rms95 ,

Thanks to the huge customization it's pretty much impossible to have it for all types (especially `@brief` is complicated with smart text and `///<summary>` style comments).

Currently working:
 - param
 - tparam
 - return

Would it be fine for you to have it only for these commands?

**Comment by rms95** [comment]
Thanks for looking into this!

For the projects I work(ed) on the tags param, tparam and return probably cover 80+% of all tags, so having automatic indentation for those sure saves a lot of work :)

**Comment by christophschlosser** [comment]
Now I have another idea on how to solve this.
I'd like to know from you which you would prefer:

1. Keep it nearly "maintenance-free" by having only the width option.
  +Already implemented
  +Less confusing for the user

2. Add an additional config parameter which can be inserted into certain templated strings
  +Easier to implement (even though it would now be additional effort)
  +More flexibility
  -Having to maintain the general width setting as well as modifying all the other settings for one effect


Example for 2 would be:
```json
"doxdocgen.generic.paramTemplate": "@param{indent}{param} "
```
resulting in
```cpp
/**
 * @param       foo This is foo
 * @param       barIsAlsoAnOption Sets bar
 */
```
or
```json
"doxdocgen.generic.paramTemplate": "@param {param} {indent}"
```
resulting in
```cpp
/**
 * @param foo                      This is foo
 * @param barIsAlsoAnOption        Sets bar
 */
```
The choice would be up to the user.

I don't want to implement 1 and later 2 because it would break 1 (and people tend not to read changelogs with autoupdating extensions).

**Comment by rms95** [comment]
Hi,

While I do see the use case for the 2nd option, I can't say I can recall a project using indentation on other places than directly after the tag. (Though I have not seen an extreme lot of projects using doxygen...)

That said, it does look like a more intuitive solution, as the template is the place where people are going to look to customize things.

> -Having to maintain the general width setting as well as modifying all the other settings for one effect

Not exactly sure what you mean with the first part, but I would think that people who care about such detail, would customize the templates anyway. I would not put those indents in the default templates, leaving it as a customization option.
When implementing option 2 I would go - if possible - for something like {indent:16} for an indent to width 16. That sounds much clearer to me than a global setting to set the width of {indent} blocks.

On a side node, there are two references you could use for the indent, either line start or block start:

Simple indent:
```c
/**
 * @param       test
 */
|<------------>| // 16
```
Option A:
```c
|<>| // Indent of 4 for the entire block
    /**
     * @param   test
     */
    |<-------->| // 12 from start of block, 16 from start of line
```
Option B:
```c
    /**
     * @param       test
     */
    |<------------>| // 16
```

In the projects I worked with, I've always seen B, though some might think differently about this.

**Comment by christophschlosser** [comment]
You asked for maximum flexibility, you get the most customization.

Current state of the implementation:

You can throw as many `{indent:<number>}` into the template string as you want.

```json
"doxdocgen.generic.paramTemplate": "@param{indent:10}{param}{indent:30}My Param doc"
```

turns into

```c++
/**
 * @param    foo                 My Param doc
 * @param    barIsAlsoAnOption   My Param doc
 */
```

The `{indent:<number>}` template can be inserted into any templabtable string.

The `<number>` indicates the character from the start of the template until where spaces are added.
So even this is valid:
```json
"doxdocgen.generic.paramTemplate": "@param{indent:10}{indent:30}{param}{indent:50}My Param doc"
```
regardless if it makes any sense it will align params at 30 and the text at 50 characters.

**Comment by christophschlosser** [comment]
Release 0.5.0 has been triggered and the update should start rolling out in the next hour.

Hope it meets your requirements, feel free to open another issue if you need anything else.
