### ISSUE TITLE
Trigger Sequence /** causes extra */ to be generated and the comment block isn't fully generated.

### ISSUE THREAD

**Issue by NeutralNoise** [christophschlosser/doxdocgen#111]
# Description

When using ```/**``` as the Trigger Sequence an extra ```*/``` is also generated because ```/*``` generates this. This doesn't let the comment get fully generated as it blocks the parser (that is my guess.) If I change the Trigger Sequence to ```//*``` the extra ```*/``` isn't generated and everything works fine. 

This didn't start happening until updated to version 1.35.0 of Visual Studio code. I also can not see a way to stop this extra ```*/``` from happening within Visual Studio Code.

### Expected result

```Cpp
	/**
	 * \brief 
	 * 
	 * \param keyID 
	*/
	void PressedKey(const UInt32 &keyID)
```

### Actual result

```Cpp
	/**
	 * \brief 
	 * 
	*/
	 */
	void PressedKey(const UInt32 &keyID)
```

**Comment by HDHarry** [comment]
I suppose  this started to happen after the latest update, which afaik introduced 
multi line comment auto-close. 
[This issue, that is , the specific code linked and its answers](https://github.com/microsoft/vscode/issues/1966#issuecomment-479404534) seems related. A workaround is proposed therein that worked for me. 
As far as I could extract however a fix requires work on vscode itself?

**Comment by platisd** [comment]
Very annoying problem that breaks the functionality of doxygen documentation extension. :cry:

**Comment by hg-zt** [comment]
Found an easy workaround, add this line into your `settings.json`:

```json
    "doxdocgen.c.triggerSequence": "///"
```

Now just type `/` three times and press return.

Note the trigger sequence is not necessarily same with the prefix of the generated comment.

**Comment by Caian** [comment]
I wonder if this is not a VSCode problem because I launched it with all extensions disabled and the "/*" sequence still triggers a "*/".

**Comment by christophschlosser** [comment]
Hi all,


thanks for the report.

This has actually been the case for quite some time now but previously we were able to overwrite and characters generated by VS Code.
It seems now that the order of events changed and we can not rely on this.
I will take a look at it and then see if we need a workaround for the `/**` style comments.

**Comment by christophschlosser** [comment]
Hi all,

I just finished working on this and triggered a new release.
The update should start rolling out in the next hour or so which should make the workarounds unnecessary.

Thank you for bringing it to my attention and providing me with the needed information and being helpful to each other! :)

**Comment by platisd** [comment]
Awesome work :+1:

**Comment by HDHarry** [comment]
Very nice 👍 👍
