### ISSUE TITLE
How do we suppress the blank line after @brief?

### ISSUE THREAD

**Issue by rib2bit** [christophschlosser/doxdocgen#112]
# Description
  
I would like to try to reproduce the [XML Documentation comment](https://docs.microsoft.com/dotnet/csharp/codedoc) style with the following configurations,
```json
{
    "doxdocgen.c.triggerSequence": "///",
    "doxdocgen.generic.paramTemplate": "<param name=\"{param}\"></param>",
    "doxdocgen.c.commentPrefix": "/// ",
    "doxdocgen.c.firstLine": "\n",
    "doxdocgen.c.lastLine": "",
    "doxdocgen.generic.returnTemplate": "<returns></returns>",
    "doxdocgen.cpp.tparamTemplate": "<typeparam name=\"{param}\"></typeparam>",
    "doxdocgen.generic.briefTemplate": "<summary>\n/// <para>{text}</para>\n/// </summary>",
    "doxdocgen.generic.boolReturnsTrueFalse": false
}
```

but a line will be inserted after brief (summary) section. How do we remove that blank line?

## Code example

```Cpp
template <class T>
bool function(T x)
{
    return true;
}
```

### Expected result

```Cpp
/// <summary>
/// <para></para>
/// </summary>
/// <typeparam name="T"></typeparam>
/// <param name="x"></param>
/// <returns></returns>
template <class T>
bool function(T x)
{
    return true;
}
```

### Actual result

```Cpp
/// <summary>
/// <para></para>
/// </summary>
///
/// <typeparam name="T"></typeparam>
/// <param name="x"></param>
/// <returns></returns>
template <class T>
bool function(T x)
{
    return true;
}
```

**Comment by christophschlosser** [comment]
Hi @rib2bit ,

currently this is not possible because I always assumed that a detailed description was needed.

I will introduce a new option to specify a configurable detailed description.

**Comment by rib2bit** [comment]
Thanks! I look forward to it.

**Comment by christophschlosser** [comment]
Hi @rib2bit ,

I just remembered I already introduced this feature.
But the new settings interface for VS Code is hiding arrays.

Take a look here:
https://github.com/christophschlosser/doxdocgen/blob/master/README.md#config-options

The key you're looking for is: `doxdocgen.generic.order`.
You will have to edit this in the `settings.json` to something like this:
```diff
"doxdocgen.generic.order": [
        "brief",
-        "empty",
        "tparam",
        "param",
        "return"
    ]
```

Please report back if this solved your problem.

**Comment by rib2bit** [comment]
@christophschlosser 

Great! I got the result what I expected.
The following settings were perfect for my purpose.
```json
"doxdocgen.c.triggerSequence": "///",
"doxdocgen.generic.paramTemplate": "<param name=\"{param}\"></param>",
"doxdocgen.c.commentPrefix": "/// ",
"doxdocgen.c.firstLine": "",
"doxdocgen.c.lastLine": "",
"doxdocgen.generic.returnTemplate": "<returns></returns>",
"doxdocgen.cpp.tparamTemplate": "<typeparam name=\"{param}\"></typeparam>",
"doxdocgen.generic.briefTemplate": "<summary>\n/// <para>{text}</para>\n/// </summary>",
"doxdocgen.generic.boolReturnsTrueFalse": false,
"doxdocgen.generic.order": [
    "brief",
    "tparam",
    "param",
    "return"
]
```
  
Thank you for the information.
