### ISSUE TITLE
File Descriptions only work for .c files and not .cpp

### ISSUE THREAD

**Issue by mwignall** [christophschlosser/doxdocgen#118]
# Description

When triggering a file description to be generated, it only works when the file's extension is .c/.h

When trying the same for a .cpp/.hpp file, only the comment block top/bottom are generated, and not the "guts" of the description

**Comment by christophschlosser** [comment]
Hi,

could you please provide a little bit more info:

- A gif of the problem

- A code snippet as the issue template requires which can be used to track down the problem

**Comment by christophschlosser** [comment]
Hi @mwignall ,

any update? Will close this soon otherwise
