### ISSUE TITLE
Getter and setter generation not working correctly

### ISSUE THREAD

**Issue by LilMouse** [christophschlosser/doxdocgen#124]
# Description

With getSomeValue and setSomevalue the generated comment is not complete
I have adjusted the param and return template to
\param {param}
\return {type}

## Code example

```Cpp
int getSomeValue()
bool setSomeValue(int value)
```

### Expected result

```Cpp
/**
 * \brief Get the some value object
 * \return int
 */
int getSomeValue()


/**
 * \brief Set the some value object
 * \return true if set correctly
 */
bool setSomeValue
```

### Actual result

```Cpp
/**
 * 
 * \param someValue 
 * \return true 
 * \return false 
*/
bool setSomeValue(int someValue);


/**
 * 
 * \return int 
*/
int getSomeValue();
```

**Comment by christophschlosser** [comment]
What does you `Brief Template` look like?

I have it set to `@brief {text}` and both code examples work for me.

**Comment by LilMouse** [comment]
Mine was empty, setting it to `\brief {text}` worked! Thanks!
