### ISSUE TITLE
Blocks for variables always have extra line

### ISSUE THREAD

**Issue by pcdangio** [christophschlosser/doxdocgen#125]
# Description
When a block is generated for a variable, an extra space is placed between the "brief" tag and the "Last Line" of the block.

Anything you'd like to add

## Code example

```Cpp
void foo;
```

### Expected result

```Cpp
/**
 * @brief Something interesting about foo.
 */
void foo;
```

### Actual result

```Cpp
/**
 * @brief Something interesting about foo.
 *
 */
void foo;
```

**Comment by christophschlosser** [comment]
This plugin only works correctly with functions/methods.

Variables, classes, namespaces and so on are not supported correctly

**Comment by Hadatko** [comment]
I have this behavior also with functions.
