### ISSUE TITLE
Implement parsing of template parameters for functions.

### ISSUE THREAD

**Issue by rowanG077** [christophschlosser/doxdocgen#13]
I am also starting work on this extensions.

Currently template parameters aren't supported at all. I am looking to implement it.

**Comment by christophschlosser** [comment]
Thank you very much!

**Comment by rowanG077** [comment]
Working on this right now.

**Comment by rowanG077** [comment]
Fixed in pull request: https://github.com/christophschlosser/doxdocgen/pull/23
