### ISSUE TITLE
Implement comment generation for classes, structs, enums and variables.

### ISSUE THREAD

**Issue by rowanG077** [christophschlosser/doxdocgen#14]
Currently comments are only generated for functions. Normally classes, structs, enums and variables also are allowed to be commented in the DoxyGen style.

**Comment by christophschlosser** [comment]
Yes indeed, many parts are still missing.
The function/method generation was the first step.

**Comment by rowanG077** [comment]
I am working on rewriting the parser to include this.

**Comment by rowanG077** [comment]
Fixed in pull request: https://github.com/christophschlosser/doxdocgen/pull/23

**Comment by christophschlosser** [comment]
I'd like to add something here.

Generating comments for access specifiers gives funny results:

```Cpp
    /**
     * @brief 
     * 
     * @param i 
     * @return public: 
     */
public:
```

**Comment by rowanG077** [comment]
WIll fix tonight. It's because access specifiers aren't yet considered keywords.

**Comment by rowanG077** [comment]
This can be closed.

**Comment by alan-gu** [comment]
Hi.
I'm on v1.3.2.
When I type /** + enter above a struct written in C, I get
```
/**
 * @brief 
 * 
 */
```
while I expect the members of the struct.
It seems this issue should have solved the problem.
An example:
```
/**
 * @brief 
 * 
 */
struct abc {
  int a;
  int b;
};
```

**Comment by cschlosser** [comment]
Could you please open a bug?
Feel free to reference this issue but I don't think the parser supports anything besides functions yet.
This issue was about doxdocgen not triggering at all.
Now it prints the most basic information, i.e. a `brief` tag and your configured comment prefixes.
