### ISSUE TITLE
could this extension used in other type, like js file?

### ISSUE THREAD

**Issue by wind4gis** [christophschlosser/doxdocgen#144]
# Description

Anything you'd like to add

## Code example

```Cpp
// Put your code here
```

### Expected result

```Cpp
/**
 * @brief Put the expected comment here
 */
```

### Actual result

```Cpp
/**
 * @brief Put the actually generated comment here
 */
```

**Comment by christophschlosser** [comment]
Yes, if the logic for these languages is implemented.

See 

* https://github.com/christophschlosser/doxdocgen/blob/db82b7b00fbfb46de813ed8a0a51fbc3669ecf0d/src/CodeParserController.ts#L114

* https://github.com/christophschlosser/doxdocgen/tree/master/src/Common

Also https://github.com/christophschlosser/doxdocgen/issues?q=is%3Aopen+is%3Aissue+label%3A%22new+languge%22
