### ISSUE TITLE
Allow for templating of the DoxyGen comment style.

### ISSUE THREAD

**Issue by rowanG077** [christophschlosser/doxdocgen#15]
Only `/**` is supported right now. But DoxyGen allow for many different formats. like `///` or even xml style comment used in C#.

So we need to implement a way to extensively configure the comments that are generated.

**Comment by rowanG077** [comment]
Implemented. See pull request https://github.com/christophschlosser/doxdocgen/pull/16

**Comment by christophschlosser** [comment]
Actually Qt Style option was added in 0.0.3 :)

But thank you very much for taking the time to bring this so much further!
