### ISSUE TITLE
custom defines are picked up in the return results

### ISSUE THREAD

**Issue by giantmustache** [christophschlosser/doxdocgen#152]
# Description

I have a function that starts with a custom define that I have defined in my compiler. The result is that the return functionality doesn't understand what the return type is.

In my case `MOCKABLE` is expanded to `virtual` and therefore the return type of this function is just `void`.

It would be nice if this plugin has a way to add defines or that it understands how the defines are being handled. In my case the define comes over the command line via cmake like so `target_compile_definitions(mastercommon_objlib PUBLIC MOCKABLE=virtual)`.

## Code example

```c++
/**
 * @brief 
 * 
 * @param networkstatus 
 * @return MOCKABLE processNetworkStatusReset 
 */
MOCKABLE void processNetworkStatusReset( const common_n::NetworkCommands_s *networkstatus );
```

### Expected result

```c++
/**
 * @brief 
 * 
 * @param networkstatus 
 */
MOCKABLE void processNetworkStatusReset( const common_n::NetworkCommands_s *networkstatus );
```

**Comment by DaanHuinink** [comment]
**If** this is considdered a problem then i can look at this. The probleem seems to be [here](https://github.com/christophschlosser/doxdocgen/blob/07b6f8998d3daa3ce3e4d56376f0b69cd6e382ec/src/Lang/Cpp/CppDocGen.ts#L264). It specifies that it will only omit the return type if it consists of a 'void' token and nothing else.

**Comment by giantmustache** [comment]
To me this is an issue, because I have to remove that line every time from the generated template. If I could just tell the plugin what words to ignore, it might be easier. I can understand that you cannot just look for "if it contains anything like void", because then you would not be able to detect void* either.

**Comment by christophschlosser** [comment]
Hi @DaanHuinink and @giantmustache ,

hope you're still using the extension. With 0.7.0 (VS Code should update automatically) this feature will be integrated and make your life easier :)
