### ISSUE TITLE
asking about param type adding

### ISSUE THREAD

**Issue by raspberryjen** [christophschlosser/doxdocgen#153]
# Description

Anything you'd like to add
I'd like to add parameter value type in param template as following.
Now, I can see only "@param str"
I couldn't find any way to add...
/**
 * @brief 
 * 
 * @param **string** str
 */
void method(string str)

**Comment by albert-github** [comment]
The doxygen syntax of the `\param` command  is (see https://www.doxygen.nl/manual/commands.html#cmdparam):
> \param '['dir']' <parameter-name> { parameter description }

only for PHP theer is a exception:
> @param  datatype1|datatype2 $paramname description

**Comment by raspberryjen** [comment]
Got it. 
There's no way to add a data type in other cases.
Thanks!
