### ISSUE TITLE
C# style xml documentation

### ISSUE THREAD

**Issue by Bondoo8** [christophschlosser/doxdocgen#156]
This extension is a great initiative and provides much needed capabilities for VS Code. Thanks.

I would like to use your extension to add xml (c# style) documentation to my code as illustrated on MarketPlace website. I have existing code from Visual Studio (Windows) that used xml documentation and I would like to keep the documentation approach consistent. 

I see that C: Comment Prefix, First Line and Last Line should likely be "///" in the settings.json fil, but I am not sure how to change "@" to < ></>.

Any suggestions on how to do this are appreciated.

![xmlstyle](https://user-images.githubusercontent.com/67067459/85038507-08723a00-b15d-11ea-8fe1-2ef76a45d9f9.png)

Thanks.

**Comment by christophschlosser** [comment]
Hi,

take a look at
```json
 // The template of the brief Doxygen line that is generated. If empty it won't get generated at all.
  "doxdocgen.generic.briefTemplate": "@brief {text}",

  // The template of the param Doxygen line(s) that are generated. If empty it won't get generated at all.
  "doxdocgen.generic.paramTemplate": "@param {param} ",

  // The template of the return Doxygen line that is generated. If empty it won't get generated at all.
  "doxdocgen.generic.returnTemplate": "@return {type} ",
```

you probably want something like `"doxdocgen.generic.paramTemplate": "<param name=\"{param}\"</param> ",` for these values.

**Comment by Bondoo8** [comment]
Thanks very much for the direction.

In case it is of use to someone, these are the lines from the settings.json file that I have implemented to try and produce C# style comments.

Note that the trigger sequence doesn't appear to work. You must hit Enter after the ///. 

    "doxdocgen.c.firstLine": "",
    "doxdocgen.c.lastLine": "/// <remarks></remarks>",
    "doxdocgen.c.commentPrefix": "/// ",
    "doxdocgen.c.triggerSequence": "///",
    "doxdocgen.generic.paramTemplate": "<param name=\"{param}\"></param>",
    "doxdocgen.generic.briefTemplate": "<summary></summary>",
    "doxdocgen.generic.returnTemplate": "<returns>{type}</returns>",
