### ISSUE TITLE
could not generate correct file header annotation

### ISSUE THREAD

**Issue by HarveyHub** [christophschlosser/doxdocgen#161]
# Description

I wrote setting in `~/.config/Code/User/setting.json` 

```json
  "doxdocgen.file.versionTag": "@version 0.1.0",
  "doxdocgen.file.fileOrder": [
    "file",
    "brief",
    "date",
    "version"
  ],
  "doxdocgen.file.fileTemplate": "@file {name}",
  "doxdocgen.generic.paramTemplate": "@param[in] {param} ",
  "doxdocgen.generic.authorTag": "@author {author} ({email})",
  "doxdocgen.generic.order": ["brief", "tparam", "param", "return"],
  "doxdocgen.generic.returnTemplate": "@return {type} ",
  "doxdocgen.generic.splitCasingSmartText": true,
  "doxdocgen.generic.filteredKeywords": ["pragma"]
``` 
## Code example

```Cpp
#pragma once
//cpp header content
//
```

### Expected result

```Cpp
/**
 * @file file_name.h
 * @brief Put the expected comment here
 * @date xxxx-xx-xx
 * @version 0.1.0
 */
```

### Actual result

```Cpp
/**
 * @brief 
 */
```

**Comment by HarveyHub** [comment]
I updated addon to lasted version 0.7.1, it could run without any errors when my header files having no template.

Here is my singleton template.
```cpp
#pragma once

template <typename T>
class Singleton
{
public:
    static T *getInstance()
    {
        static T instance;

        return &instance;
    }
};

```

When I pressed `/** + enter`, it could not generate correct file header annotation, which like
```cpp
/**
 * @brief 
 */
#pragma once

template <typename T>
class Singleton
{
public:
    static T *getInstance()
    {
        static T instance;

        return &instance;
    }
};
```

My computer information as following
- Version: 1.46.1
- Commit: cd9ea6488829f560dc949a8b2fb789f3cdc05f5d
- Date: 2020-06-17T21:13:08.304Z (1 wk ago)
- Electron: 7.3.1
- Chrome: 78.0.3904.130
- Node.js: 12.8.1
- V8: 7.8.279.23-electron.0
- OS: Linux x64 4.15.0-106-generic

*Note*:
> I have restarted vscode and  reboot computer for serveral times, it doesn't work.

**Comment by christophschlosser** [comment]
You're on line 1?

**Comment by HarveyHub** [comment]
yes!
