### ISSUE TITLE
Enhancement: Vala support

### ISSUE THREAD

**Issue by aeldemery** [christophschlosser/doxdocgen#167]
# Vala Support

Since Vala syntax inherit form C#, I think it wouldn't be too difficult to add support for. 
The open-source community would appreciate your work if you could address this.

Thanks

**Comment by christophschlosser** [comment]
Currently there is not even C# support.
So if you want to contribute feel free to do so.

**Comment by aeldemery** [comment]
Thanks for replying. I would like to do, if I know how. Unfortunately I don't speak Typescript. 
But out of interest, how/where to start to add support for a new language?

**Comment by aeldemery** [comment]
I think this could be closed. Thanks
