### ISSUE TITLE
Automatic asterisk at start of a new line

### ISSUE THREAD

**Issue by deg0nz** [christophschlosser/doxdocgen#22]
Hey,

I have many comments that need more specific description of functions. 
It would be nice, if  a new line inside of the doxygen comment section automatically starts with an asterisk.

Currently, a new line is created like this:

``` C
/**
 * @brief
 * 
 * Blah Blah, Blubb
 * [New line ceated here]
<-- (Cursor here, no asterisk)
 * @param foo Does bar.
 */
```

P.S.: Thank you for the fast reactions on my previous issues :) I Appreciate it :)

**Comment by christophschlosser** [comment]
Hey!

I'm not quite sure what the problem is.

Could you add a bit more detail (maybe even a gif?) when the generated line starts without an asterisk?

**Comment by deg0nz** [comment]
Hmm... gif would be tricky for some reasons.... sorry
I try to explain it otherwise:

Some IDEs (like Eclipse afaik) automatically create a new line matching the current comment style when creating a new line in the comment. For example by adding an asterisk at the beginning of a new line when using multi-line comments.

Currently, when I press return in a comment to create a new line, it just creates a new line. When I want the new line to look like all the other ones, I have to ass an asterisk to the new line manually.

Another example:

This is the original comment:
``` C
/**
 * @brief
 * 
 * Blah Blah, Blubb
 */
```

When I just add some new lines after "Blah, Blah, Blubb" to this comment, It looks like this:
``` C
/**
 * @brief
 * 
 * Blah Blah, Blubb




 */
```

But it would be nice, if it looks like this:

``` C
/**
 * @brief
 * 
 * Blah Blah, Blubb
 *
 *
 *
 *
 */
```

I hope, this makes it more clear

**Comment by christophschlosser** [comment]
I'm not quite sure that this is a problem with this extension but more with how VS Code deals with comments.

Just to be clear:

```
/**
 * @brief
 * 
 * Blah Blah, Blubb<cursor position>
 */
``` 

Case 1: Now you press  *enter* when the cursor is at the last character of *Blubb*

This is what happens for me then:

```
/**
 * @brief 
 * 
 * Blah Blah, Blubb
 * <cursor position>
 */
```

Case 2: If I copy a block of newlines and insert it (using crtl-c + ctrl-v) I get this result:

```
/**
 * @brief 
 * 
 * Blah Blah, Blubb
 * 

<cursor position>
 */
```

Is case 1 or 2 what you're doing?

**Comment by deg0nz** [comment]
Yeah, I was in doubt too, if this is a problem with the editor itself... Not with the extension.

I'm doing case 1 and no asterisk is added to the new line. Do you mean this could be a configuration in the editor?

**Comment by deg0nz** [comment]
OK, I just found a workaround for this (sometimes googling helps ;) ). 
I installed the [Auto Comment Blocks](https://marketplace.visualstudio.com/items?itemName=kevinkyang.auto-comment-blocks) extension and reinstalled your extension, now everything works as expected.

I don't know, if your extension should handle this... It's your decision.
It works for me now though...

**Comment by christophschlosser** [comment]
Actually there's another way to do this (at least it worked for me on a clean VS Code install):

You need the C/C++ extension from Microsoft [ms-vscode.cpptools](https://marketplace.visualstudio.com/items?itemName=ms-vscode.cpptools).
If the extension is installed VS Code will add the asterisk.

**Comment by christophschlosser** [comment]
Maybe I'll add this to the docs somewhere.

**Comment by amordo** [comment]
@

> Actually there's another way to do this (at least it worked for me on a clean VS Code install):
> 
> You need the C/C++ extension from Microsoft [ms-vscode.cpptools](https://marketplace.visualstudio.com/items?itemName=ms-vscode.cpptools). If the extension is installed VS Code will add the asterisk.

Users could use another code-helper engine (eg. clangd) and often such extensions don't get along together.
It would be nice to exclude this dependency.
