### ISSUE TITLE
Create tests for C++ parsing

### ISSUE THREAD

**Issue by rowanG077** [christophschlosser/doxdocgen#24]
Since right now I think we have decent C++ support I would like to add testing to it so it will automatically test a variety of cases and we can move faster to support other languages.

I believe it might be best to start with refactoring out the parses from the editor stuff. This way we can make tests easier for just the parser without having to worry about visual studio code editor stuff.

**Comment by christophschlosser** [comment]
Great idea.
This is something I also wanted to get behind now.
