### ISSUE TITLE
Support for more languages

### ISSUE THREAD

**Issue by rowanG077** [christophschlosser/doxdocgen#25]
We are close to having C++ support down and the next step would be supporting more languages. I have a preference for C# or Python. Any other suggestions?

**Comment by aHg9aejba** [comment]
How about c++/cli?

**Comment by christophschlosser** [comment]
I don't know. I don't know c++/cli.
Can you create a new issue with some code examples?

**Comment by christophschlosser** [comment]
I'm gonna close this so people will open up their own issues if they want a new language added.
