### ISSUE TITLE
How to use the extension settings?

### ISSUE THREAD

**Issue by vbotics** [christophschlosser/doxdocgen#29]
Thank you for the great work creating Doxygen Documentation Generator for VS Code. I would like to know how can I access the settings to do the commenting style as shown in the wiki: 
![image](https://user-images.githubusercontent.com/10283521/32539110-61de57a4-c48e-11e7-9530-98068c04d591.png)

especially using /brief, /param, /author tags etc..

Thanks a lot :+1:

**Comment by rowanG077** [comment]
I will write up a short guide tonight.

**Comment by christophschlosser** [comment]
Hey @vbotics 
just a quick heads-up:
Open the settings dialog -> search for "doxygen" -> look for the options starting with doxdocgen.generic. and edit them to your liking in the user settings.

For your case you probably want this in your settings
```json
    "doxdocgen.generic.briefTemplate": "\brief ",
    "doxdocgen.generic.paramTemplate": "\param {param} ",
    "doxdocgen.generic.returnTemplate": "\return {type} "
```

**Comment by vbotics** [comment]
@christophschlosser Cool that worked like a charm :+1: Thank you :)
