### ISSUE TITLE
can not add function comment in *.c file

### ISSUE THREAD

**Issue by zt449569708** [christophschlosser/doxdocgen#40]
# Description

can not add function comment in *.c file

**Comment by christophschlosser** [comment]
Thanks for the headsup.
Will look into it.

**Comment by christophschlosser** [comment]
Could you share the .c file or at least the function?

It works for me with .c and .cpp files.

**Comment by zt449569708** [comment]
@christophschlosser OK.
I use "doxdocgen" plugin.  The results are as follows
```c
/**
 * 
int main(void)
{
	return 0;
}
```
But I use "C-family Documentation Comments" plugin,it can works.
```c
/** 
 * @brief  
 * @note   
 * @retval 
 */
int main(void)
{
	return 0;
}
```

**Comment by zt449569708** [comment]
@christophschlosser How to share the .c file? Email or something else?

**Comment by christophschlosser** [comment]
This is what is generated for me:
```C
/**
 * @brief 
 * 
 * @param void 
 * @return int 
 */
int main(void)
{
	return 0;
}
```

Is VS Code detecting your language to C? (In the lower right corner of the blue bar does it say 'C' next to the feedback smiley?)
Do you have the C/C++ tools from MS installed? (https://marketplace.visualstudio.com/items?itemName=ms-vscode.cpptools)

You can create a Gist with the file contents if you want to share it. But I don't think it's not necessary.

**Comment by zt449569708** [comment]
@christophschlosser Yes，it is a C file. But  it can work in *.cpp file.

**Comment by christophschlosser** [comment]
Ok this is really strange.
What version of the plugin are you using?
Have you changed your config?

**Comment by zt449569708** [comment]
@christophschlosser Version is 0.0.7.And the configuration has not been modified.

**Comment by christophschlosser** [comment]
You have the MS C/C++ tools installed and if you change the file to C++ it's working?

**Comment by christophschlosser** [comment]
@HarbourXbr 
> I need to convert C files into CPP files and convert them back to C. I need to do this every time when i open the VSCode.then it works.

I will take a look at this as soon as I can get around to it. This is utterly annoying.

**Comment by HarbourXbr** [comment]
@christophschlosser thanks

**Comment by christophschlosser** [comment]
Should be fixed now.
It will be in release 0.0.8
