### ISSUE TITLE
can not add function comment in *.c file

### ISSUE THREAD

**Issue by HarbourXbr** [christophschlosser/doxdocgen#41]
# Description

Anything you'd like to add

## Code example

```Cpp
// Put your code here
```

### Expected result

```Cpp
/**
 * @brief Put the expected comment here
 */
```

### Actual result

```Cpp
/**
 * @brief Put the actually generated comment here
 */
```

**Comment by HarbourXbr** [comment]
I need to convert C files into CPP files and convert them back to C.
I need to do this every time when i open it.

**Comment by HarbourXbr** [comment]
then it works

**Comment by christophschlosser** [comment]
I added your observation to #40
