### ISSUE TITLE
'///' doesn't trigger method

### ISSUE THREAD

**Issue by but0n** [christophschlosser/doxdocgen#61]
# Description

MacOS

## Code example

```Cpp
///
```

### Expected result

```Cpp
///


```

### Actual result

```Cpp
///
/// @brief Put the actually generated comment here
/// @param ...
...
```

**Comment by christophschlosser** [comment]
Could you please be more specific?

Did you set the option "doxdocgen.generic.triggerSequence": "///"?

Could you please paste your modified values for doxdocgen settings?

What version of VS Code and doxdocgen are you running?

**Comment by but0n** [comment]
Sorry, I'm new to vscode 😭, I didn't know how to config the plug-in, I haven't set `"doxdocgen.generic.triggerSequence": "///"?` before, now it's working with '///'

Thank you!

**Comment by christophschlosser** [comment]
No problem, no damage done :)

I've added the config options to the README to make it easier for new comers of VS Code and this addon.

See: https://github.com/christophschlosser/doxdocgen#config-options

**Comment by gsabater** [comment]
@christophschlosser is this config option implemented? I don't see the `"doxdocgen.generic.triggerSequence"` option anywhere, and i would love to use this plugin for php and js primarly

**Comment by christophschlosser** [comment]
Hey @gsabater, there's a reason for that.

See https://github.com/christophschlosser/doxdocgen/releases/tag/0.3.0#config-update

The key is now called "doxdocgen.c.triggerSequence".
The plugin is not compatible with js or php. Currently only C and C++ are supported. If you'd like to add support for JS and/or PHP feel free to do so.

**Comment by gsabater** [comment]
@christophschlosser Thanks, i saw the doxdocgen.c.triggerSequence, but i though that the generic existed as well.

I don't think i have the knowledge to implement the support to other languages, but I guess that giving it a try won't hurt.

Thanks for your time.

**Comment by christophschlosser** [comment]
> I don't think i have the knowledge to implement the support to other languages, but I guess that giving it a try won't hurt.

Feel free to try. In case you're stuck somewhere maybe we can finish it together.
