### ISSUE TITLE
How do you trigger  file heading autogeneration?

### ISSUE THREAD

**Issue by Makogan** [christophschlosser/doxdocgen#70]
In the examples it si shown that file description templates get Automatically generated.

However I can't get DDG to generate the file descriptions for me.

**Comment by christophschlosser** [comment]
Could you please use the provided issue template?

It would make it easier for me to understand your problem.

Anyway please fill in the following gaps:

## Description
Please tell me a bit more about your file, line numbers where you attempt the trigger and if/what you modified in your config.

## Code example

```Cpp
// Put the first content line, like #include <stdio.h>, of your file here
```

**Comment by Makogan** [comment]
have noticed the following pattern. 

In visual studio code, if you create a new file and start adding the documentation (i.e start typing /**)

The file template description does get generated

However if there are any comments or code on teh file it wont

# Description

This happens for any cpp and hpp files that already contain code

# Code example
//Typing /** does not start file description aut generation
void set_log_file(string path);

**Comment by christophschlosser** [comment]
Ok thank you.

Could you please try with #include <someHeader.h> on the line after your comment generation?

If it works I have to improve the file detection. 
https://github.com/christophschlosser/doxdocgen/blob/482ed941aab73230a560024e37c272b1b398b48a/src/Lang/Cpp/CppParser.ts#L418
https://github.com/christophschlosser/doxdocgen/blob/482ed941aab73230a560024e37c272b1b398b48a/src/Lang/Cpp/CppParser.ts#L419

**Comment by sdbbs** [comment]
Thanks @cschlosser - I did not want to reopen this bug, just to notify that this worked:

> Could you please try with #include <someHeader.h> on the line after your comment generation?

.... this is how it looks with v1.4.0 of the extension:

![2023-01-03_vscode_doxdocgen](https://user-images.githubusercontent.com/48317456/210303236-59b5d30c-d03e-4a5a-be0d-9350a348f79f.gif)

Thanks for the great extension!
