### ISSUE TITLE
Doesn't parse cpp member pointer names correctly

### ISSUE THREAD

**Issue by CollinDietz** [christophschlosser/doxdocgen#78]
# Description

When generating a doxy comment for a function that takes a member pointer parameter it uses the second piece of the member pointer type instead of the parameter name 

## Code example

```Cpp
class foo
{
    int bar;
}

void test(int foo::* memberPointer);
```

### Expected result

```Cpp
class foo
{
    int bar;
}

//! \brief 
//! \param memberPointer
//! \return  
void test(int foo::* memberPointer);
```

### Actual result

```Cpp
class foo
{
    int bar;
}

//! \brief 
//! \param foo:: 
//! \return  
void test(int foo::* memberPointer);
```

**Comment by rowanG077** [comment]
Wow I C++ feature I actually didn't know about. I will fix this up next weekend.

**Comment by christophschlosser** [comment]
@rowanG077 what's your status on this?
