### ISSUE TITLE
Separate C++ from C settings

### ISSUE THREAD

**Issue by ronshe** [christophschlosser/doxdocgen#84]
# Just add other settings to C++

## C settings (as today):
```json
  "doxdocgen.c.commentPrefix": " * ",
  "doxdocgen.c.firstLine": "/**",
  "doxdocgen.c.lastLine":  " */",
  "doxdocgen.c.triggerSequence": "/**",
```
## C++ settings (new):
```json
  "doxdocgen.cpp.commentPrefix": "/// ",
  "doxdocgen.cpp.firstLine": "///",
  "doxdocgen.cpp.lastLine":  "///",
  "doxdocgen.cpp.triggerSequence": "///",
```

**Comment by christophschlosser** [comment]
Just to be clear.
You want to have different settings for C++ and C? Or do you want to rename them?

**Comment by ronshe** [comment]
Different settings.
C++ comments are a lot better, but in ANSI C we cannot use them.

Best regards,
Ronny Sherer

**Comment by christophschlosser** [comment]
Okay I'm still not sure I get your problem.

This is confusing to me:
> C++ comments are a lot better, but in ANSI C we cannot use them.

Could you please post a whole usecase and tell me what you mean by this?

**Comment by christophschlosser** [comment]
Closing this as there is no sufficient description.
