### ISSUE TITLE
Conflict to other extension

### ISSUE THREAD

**Issue by LeThiHyVong** [christophschlosser/doxdocgen#85]
# Description
I see your work have conflict to 2 extensions that both handles /** multiline comment style:
- [Auto Comment Block](https://marketplace.visualstudio.com/items?itemName=kevinkyang.auto-comment-blocks): if Auto Comment Block catch the /** first then your extension parse incorrectly (like the example below). I use this since Cpp-tools can't expanse multiline comment to the end */.
## Code example

```Cpp
int MovePosXYAcc(const tsCOODXY * const ptPosXY);
```

### Expected result

```Cpp
/**
 * @brief 
 * 
 * @param ptPosXY 
 * @return int 
 */
```

### Actual result

```Cpp
/**
 * @brief 
 * 
 */
```
- [Cpp-tools](https://marketplace.visualstudio.com/items?itemName=ms-vscode.cpptools): it parses correctly but a little bit late (about 2 seconds after Enter).

I doubt these ones can be solved, but at least please update your instruction manual. 
Thanks.

**Comment by christophschlosser** [comment]
Thank you for using the template!
This addon doesn't handle only `/**` but any trigger sequence you specify (e.g. `///` for XML style or `/*!` for Qt style). It is your obligation to setup your workstation correctly.

As far as I understood your request here's how to solve it: The functionality you described for auto comment block is included in this addon as well so there is no need to have both of them.

**Comment by LeThiHyVong** [comment]
Sure, I know that. 
I just hope you update this to the official doc to make sure no one get stuck in same problem like me.

**Comment by christophschlosser** [comment]
I'm still not sure where you're getting at. I'm not gonna list any addon which may or may not be compatible with this one (which could change in versions as well).
