### ISSUE TITLE
doxdocgen interprets keywords before void as return value

### ISSUE THREAD

**Issue by deg0nz** [christophschlosser/doxdocgen#9]
Hi christoph,

First of all: Thanks for creating this plugin. It makes commenting in VSCode really handy.

Here's the issue:
When a function is declared as `static inline void` in C, the plugin recognizes it as a return value.
For example, when my function is named `static inline void foo_bar()`, I get the following automated doxygen comment:

``` C
/**
 * @brief 
 * 
 * (Detailed description)
 * 
 * @return static inline void
 */
static inline void foo_bar()
```

Greetings!

**Comment by deg0nz** [comment]
I also tested it with the `inline` and `static` keywords as the only ones before `void`. The behaviour is the same.
So functions like `inline void foo_bar()` and `static void foo_bar()` produce the same issue.

**Comment by christophschlosser** [comment]
Hi @deg0nz !

Thank you for this positive feedback! :)

Thank you for taking the time to report this, I will look into it!

**Comment by christophschlosser** [comment]
@deg0nz check your Extension updates in VSCode ;)
