### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by JacquelinLouis** [christophschlosser/doxdocgen#96]
- Issue Type: `Performance`
- Extension Name: `doxdocgen`
- Extension Version: `0.4.1`
- OS Version: `Linux x64 4.15.0-43-generic`
- VSCode version: `1.30.1`

[cschlosser.doxdocgen-unresponsive.cpuprofile.txt](https://github.com/christophschlosser/doxdocgen/files/2711972/cschlosser.doxdocgen-unresponsive.cpuprofile.txt)

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by rowanG077** [comment]
Hmmm I looked at the profile and the `getTemplate` function in `CppParser.ts` is the culprit it takes `94%` of the total time. Quickly scanning over the code I don't see anything wrong.

Can you provide an example how your profile was taken so I can look into it in detail?

**Comment by christophschlosser** [comment]
@rowanG077 Only thing I can think off right now is an extemely long line was captured and the expression search loop doesn't find a '<' or there are no whitespaces.

@JacquelinLouis Could you please also provide us with your config settings for Doxdocgen?

**Comment by JacquelinLouis** [comment]
Sure ! Did you mean this one ?
[doxygen.txt](https://github.com/christophschlosser/doxdocgen/files/2718354/doxygen.txt)

**Comment by JacquelinLouis** [comment]
No, I didn't change them.

**Comment by christophschlosser** [comment]
Could you please provide an example piece of code where this happens for you?

**Comment by christophschlosser** [comment]
This is unfortunate.
Can you reproduce it with another (non company) example?
