### ISSUE TITLE
Trigger sequence /** does not work

### ISSUE THREAD

**Issue by dave2k19** [christophschlosser/doxdocgen#97]
Issue Type: ?
Extension Name: doxdocgen
Extension Version: 0.4.1
OS Version: Windows 7 Enterprise
VS version: 14.0.25431
VSCode version: 1.30.2

Hi,

I have installed the plugin through VSCode but no matter what I do the trigger sequence does not work in my code.
I tried to apply it to existing code and also to newly created files (c and cpp) but it just did not trigger. I verified that the plugin is installed and enabled. I also tried different version (0.1 and 0.3) but nothing changed.
I also tried to change the sequence itself - but to no avail.
Are there any requirements that I have missed or do I need to disable auto-completion of some sort?

Example code
test.cpp

void func(int a) {
    return;
}

**Comment by JasonChu1313** [comment]
I encounter this problem as well.

**Comment by christophschlosser** [comment]
Unfortunately I don't have a windows machine around at the moment and my macOS setup works.

Could you please take a look into the JS console of VS Code? Take a look into `Help > Toggle Developer Tools` for this.
A list of your plugins and settings would also be really helpful.

Is vscode detecting your file as C/C++? It should show you in the lower right corner.

**Comment by JasonChu1313** [comment]
Thanks for your reply. Actually, I test it on my mac, and it works for C and C++ but it didn't work for C#, but I think it also supports C# right? Do I need to do some extra configuration for it to work for dot cs file?

**Comment by christophschlosser** [comment]
No, right now it‘s only C and C++.

**Comment by JonMcDevitt** [comment]
I also encounter this problem. I have attached a zipped .mp4 recording of the issue. Is this not the correct way to configure and use the Doxygen extension?

[VSCode_DoxygenExt.zip](https://github.com/christophschlosser/doxdocgen/files/2784088/VSCode_DoxygenExt.zip)

**Comment by dave2k19** [comment]
Hi Christoph,
sorry for late reply. I got a few plugins and I will report them tomorrow.
This is the JS console of VS code:
![image001](https://user-images.githubusercontent.com/46692152/51640093-e45bfa80-1f62-11e9-9cdc-5c4599b9337d.png)
Is that what you are looking for? It does not strike as informative.

**Comment by dave2k19** [comment]
My plugins:
- Azure AD Authentification Connected Service, V 1.1
-  CppTrippleSlash V1.0.6
- Developer Analytics Tools V 7.0.206221
- Get Xamarin V 1.0.0.0
- MicroProfiler V1.4.605.0
- Microsoft .NET and Web Tools V 14.1.11107.0
- Microsoft .NET Web Frameworks and Tools V. 5.2.40314.0
- Microsoft Azure Mobile Services V. 2.0
- Microsoft Azure Storage 1.1
- Microsoft Connected Services V 2.0
- Microsoft Office 365 API Tools V 1.6
- MySQL 1.2.8
- NuGet Package Manager 3.4.4.1321
- TypeScript 1.8.36
- Viasfora 4.2.188
- Extension for TextMate Grammars 1.1

**Comment by christophschlosser** [comment]
Hi @dave2k19,

Thank you for your feedback.
Regarding the console you were very close. Please take a look at the `Console` tab right to the `Elements` tab you screenshotted for me.

These plugins appear to be **Visual Studio** plugins which don't work with **VS Code** (at least to my knowledge).
Could you please provide me with a list of **VS Code** plugins?

**Comment by dave2k19** [comment]
Hi @christophschlosser,

thanks. Sorry I could not check back over the weekend.
Not sure whether these screenshots help:

![plugins_vs_code](https://user-images.githubusercontent.com/46692152/51860601-7c2e5f80-233a-11e9-9f59-4f4534237841.PNG)
![vs_code](https://user-images.githubusercontent.com/46692152/51860611-818baa00-233a-11e9-8996-8ab8e9f3ade4.PNG)

**Comment by christophschlosser** [comment]
Hi @dave2k19 
Thank you very much!
These helped me in eliminating possibilities but don't solve the problem unfortunately.

Could you please do me another favor and record a short video?
Your settings.json would also be really helpful.

**Comment by dave2k19** [comment]
Hi @christophschlosser,
sorry for late reply again. I shot a video showing that the plugin is active and the c trigger sequence is "/**".
Secondly, it shows that nothing happens after the trigger sequence is executed.
https://quickfileshare.org/Unh/20190204_211735.zip

If I found the correct settings.json, it is quite slim. I searched my entire C drive.
settings.json
{
    "doxdocgen.generic.newLineAfterParams": true,
    "window.zoomLevel": 0
}

**Comment by rowanG077** [comment]
@dave2k19 

You aren't coding in visual studio code. You are running visual studio. This plugin only works for visual studio code.

**Comment by jvlker** [comment]
I got the same problem. Typing /** + Enter in .h or .cpp-files doesn't work. Here are my plugins: 
![screenshot from 2019-02-04 21-26-15](https://user-images.githubusercontent.com/4425214/52258375-36b3f880-291f-11e9-8508-24e5d7595b86.png)

And these are the only logs in the console not comming from CMakeTools after a fresh start of vscode and trying 3 times to get the doxygen-generation:
![screenshot from 2019-02-05 08-28-51](https://user-images.githubusercontent.com/4425214/52258630-27817a80-2920-11e9-9023-7ce1ccfe2184.png)

**Comment by rowanG077** [comment]
@jvlker 

Can you post a video of the issue? This has been open for weeks now and no one has posted a way to reproduce or actually shown that it doesn't work.

**Comment by jvlker** [comment]
![doxygen](https://user-images.githubusercontent.com/4425214/52267598-bbac0b80-2939-11e9-8988-7828defa6ce5.gif)

I also tried a new empty project and in a single main.cpp file it seems to work...

**Comment by jvlker** [comment]
I played a bit around with the settings and it seems, that the `editor.formatOnSave` is responsible. When I switch to false (and restart vscode), doxygen works. But the reformatter is more important than doxygen for me...

**Comment by rowanG077** [comment]
I can't seem to reproduce it. I installed the C/C++ Microsoft extension to use it's formatter and the plugin works for me. Would you be willing to run the plugin in debug mode together with me via screenshare or something and checking out what is going wrong?

**Comment by jvlker** [comment]
@rowanG077 sure, can you send me an email?

**Comment by bytesoftly** [comment]
Got the same problem here, any progress?

**Comment by rowanG077** [comment]
@jvlker issue got resolved after restarting VS Code. @bytesoftly since you seem to be the only who still has this issue can you post a gif/movie of it not working. I can look into it on the weekend if I can reproduce it.

**Comment by bytesoftly** [comment]
@rowanG077 Ah same problem here, all good and awesome plugin.

**Comment by Jacques-eMediaIT** [comment]
Facing this issue on the latest version (1.4.0). Windows 10. Latest VS Code version. TS file. Can't get the trigger sequence to work.

**Comment by cschlosser** [comment]
@Jacques-eMediaIT  could you please open a new issue and maybe reference this one with more details and videos of your problem?

**Comment by shiretu** [comment]
I have same problem: typing `/**` with or without `Enter` does not trigger the generator. When I press `Enter` it just adds a new commented line, resulting in this overall form:
```
/**
* */
```

**Comment by matiasdiaz21** [comment]
![image](https://user-images.githubusercontent.com/36611421/196582819-2f98bc81-03e3-40a6-9203-0fc56c89c173.png)

Same problem here. tap /** and Enter and not work

**Comment by rowanG077** [comment]
Just to note this plugin only works for C/C++ not for other languages.

**Comment by Athanaze** [comment]
Is there a fix ? I have the same issue.
