### ISSUE TITLE
Trigger sequence '///' doesn't give expected result

### ISSUE THREAD

**Issue by SoftwareApe** [christophschlosser/doxdocgen#98]
# Description

When using '///' as trigger sequence I don't get the doxygen comment with the same leading characters.

## Code example

In an empty `.cpp` file typing `///` and pressing return gives me 
```Cpp
/**
 * @file Untitled-1
 * @author your name (you@domain.com)
 * @brief 
 * @version 0.1
 * @date 2019-01-29
 * 
 * @copyright Copyright (c) 2019
 * 
 */
```
### Expected result

```Cpp
/// @file Untitled-1
/// @author your name (you@domain.com)
/// @brief 
/// @version 0.1
/// @date 2019-01-29
///
/// @copyright Copyright (c) 2019
```
My company's coding guidelines forbid the usage of multiline comments. It would be really helpful if this could be context sensitive.

**Comment by christophschlosser** [comment]
Hi Carl,

thank you for your great description!

The trigger sequence doesn't change the comment that is generated. This is helpful for muscle memory but you can configure the generated output independently.

Please take a look at: https://github.com/christophschlosser/doxdocgen#config-options

The settings you want to take a closer look at are probably:
```json
// The prefix that is used for each comment line except for first and last.
"doxdocgen.c.commentPrefix": " * ",

// The first line of the comment that gets generated. If empty it won't get generated at all.
"doxdocgen.c.firstLine": "/**",

// The last line of the comment that gets generated. If empty it won't get generated at all.
"doxdocgen.c.lastLine": " */",
```

Changing them to:
```
"doxdocgen.c.commentPrefix": " ///",
"doxdocgen.c.firstLine": "///",
"doxdocgen.c.lastLine": " ///",
```

should give you the desired output.

Feel free to report back once you get a chance to try it out.

**Comment by SoftwareApe** [comment]
Wow, thanks for the quick feedback. It does seem to work. Although it still generates a last line even is lastLine is empty. Although it seems to add two last lines if it isn't, i.e. for
```json
"doxdocgen.c.commentPrefix": "",
"doxdocgen.c.firstLine": "///",
"doxdocgen.c.lastLine": "",
```

I get

```cpp
///@file Untitled-1
///@author your name (you@domain.com)
///@brief 
///@version 0.1
///@date 2019-01-29
///
///@copyright Copyright (c) 2019
/// <- this line here seems unnecessary
```
That's just a minor nitpick though.

**Comment by christophschlosser** [comment]
Hi,

happy to help :)

I may have the solution to your other problem as well:
```
"doxdocgen.file.fileOrder": [
    "file",
    "author",
    "brief",
    "version",
    "date",
    "empty",
    "copyright",
    "empty",
    "custom"
  ],
```

This is the default order and fields which get generated for files. As you can see there is an empty line after the copyright before the custom one.

Changing this to:
```
"doxdocgen.file.fileOrder": [
    "file",
    "author",
    "brief",
    "version",
    "date",
    "empty",
    "copyright"
  ]
```
should do the trick.

**Comment by SoftwareApe** [comment]
Thank you!
