### ISSUE TITLE
How to generate documentation?

### ISSUE THREAD

**Issue by TechnoBuddhist** [christophschlosser/doxdocgen#99]
# Question

How do I generate the documentation when I've added all the doxy comments using your extension?

**Comment by rowanG077** [comment]
Use doxygen just like you would normally. This has nothing to do with this plugin.

**Comment by TechnoBuddhist** [comment]
That did occur to me but I assumed this extension was all in one!  Cheers!!

**Comment by joaompfe** [comment]
I came here from this [review](https://marketplace.visualstudio.com/items?itemName=cschlosser.doxdocgen&ssr=false#review-details) in Visual Studio marketplace and you @christophschlosser  said this plugin generate documentation. I have put comments but how do I generate the documentation files? Do I need to use Doxywizard? Thanks

**Comment by christophschlosser** [comment]
This extension only generates comments from code. Not files.
You will still have to run doxygen on your source code files as you did without the extension.
